<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-UltimaMilla.Worker-757cfb6b-fc28-4a69-8e3b-16ba20e592da</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\UltimaMilla.Domain.csproj" />
    <ProjectReference Include="..\Application\UltimaMilla.Application.csproj" />
  </ItemGroup>
</Project>
